name: Build
on: [push]
env:
  GOPRIVATE: "github.com/paulhammond"
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: ["mac", "linux"]
      fail-fast: false

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build
        env:
          OS: ${{ matrix.os }}
          REF: ${{ github.sha }}
        run: "./.github/workflows/build.sh"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "jp-${{matrix.os}}-${{github.sha}}.tgz"
          path: "jp-${{matrix.os}}-${{github.sha}}.tgz"
