name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        # https://github.com/cli/cli/issues/9558
        with:
          ref: ${{ github.ref }}
      - name: Generate Notes
        run: |
          mkdir -p build
          git tag -l --format='%(contents:body)' "${{github.ref_name}}" > build/notes.md
          echo >> build/notes.md
          echo "[Build log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> build/notes.md
      - name: Create Release
        run: gh release create --notes-file build/notes.md "${{github.ref_name}}"
        env:
          GH_TOKEN: ${{ github.token }}
  build:
    name: Build
    needs: create-release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: ["macos", "linux"]
        arch: ["arm64", "amd64"]
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Test
        run: go test -v ./...
      - name: Build
        env:
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}
          REF: ${{ github.ref_name }}
        run: "./.github/workflows/build.sh"
      - name: Upload
        run: gh release upload "${{github.ref_name}}" build/jp-${{matrix.os}}-${{matrix.arch}}-${{github.ref_name}}.tgz
        env:
          GH_TOKEN: ${{ github.token }}
