name: Test
on: [push]
env:
  GOPRIVATE: "github.com/paulhammond"
jobs:
  go:
    name: Go
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test
        run: go test -v .
